version: "3.5"

networks:
  public: {}

volumes:
  grafana_data: {}
  prometheus_data: {}
  minio_data: {}
  thanos-store_data: {}

services:
  prometheus:
    depends_on:
      - thanos-sidecar
    image: prom/prometheus:v2.14.0
    # Set user to root, otherwise shared tsdb directory is not readable by one of the instances
    user: root
    ports:
      - 19090:9090
    networks:
      - public
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus:/etc/prometheus
    command:
      - --web.listen-address=0.0.0.0:9090
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --log.level=info
      # theses settings are needed for thanos
      - --web.enable-admin-api
      - --storage.tsdb.retention.time=6h
      - --storage.tsdb.min-block-duration=2h
      - --storage.tsdb.max-block-duration=2h
  thanos-sidecar:
    image: thanosio/thanos:v0.9.0
    # Set user to root, otherwise shared tsdb directory is not readable by one of the instances
    user: root
    volumes:
      - prometheus_data:/prometheus
      - ./config/thanos:/config
    networks:
      - public
    command:
      - sidecar
      - --log.level=info
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:10902
      - --prometheus.url=http://prometheus:9090
      - --tsdb.path=/prometheus
      - --objstore.config-file=/config/bucket_config
    ports:
      - 10902:10902

  thanos-query:
    image: thanosio/thanos:v0.9.0
    networks:
      - public
    command:
      - query
      - --log.level=info
      - --query.auto-downsampling
      - --query.partial-response
      - --query.replica-label=replica
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:10902
      - --store=thanos-sidecar:10901
      - --store=thanos-store:10901
    ports:
      - 11902:10902
  thanos-store:
    # S3 storage must be accessible before starting store for this demo
    depends_on:
      - minio
    image: thanosio/thanos:v0.9.0
    volumes:
      - thanos-store_data:/data
      - ./config/thanos:/config
    networks:
      - public
    command:
      - store
      - --log.level=info
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:10902
      - --data-dir=/data
      - --objstore.config-file=/config/bucket_config
    ports:
      - 12902:10902

  grafana:
    image: grafana/grafana:6.5.1
    ports:
      - 13000:3000
    networks:
      - public
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pass
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=warn

  node-exporter:
    image: prom/node-exporter:v0.18.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
    # Do not bind ports to be able to scale
    #ports:
    #  - 19100:9100
    networks:
      - public

  minio:
    image: minio/minio
    volumes:
      - minio_data:/export
    ports:
      - 19000:9000
    environment:
      - "MINIO_ACCESS_KEY=key"
      - "MINIO_SECRET_KEY=secretkey"
      - "MINIO_PROMETHEUS_AUTH_TYPE=public"
    entrypoint: sh
    command: -c 'mkdir -p /export/bucket001 && mkdir -p /export/bucket002 && mkdir -p /export/bucket003 && /usr/bin/minio server /export'
    networks:
      - public

  redis-server:
    image: redis:5.0.7
    ports:
      - 16379:6379
    networks:
      - public

  redis-exporter:
    image: oliver006/redis_exporter:v1.3.4
    ports:
      - 19121:9121
    networks:
      - public
    command:
      - "--redis.addr=redis://redis-server:6379"

  alertmanager:
    image: prom/alertmanager:v0.19.0
    ports:
      - 19093:9093
    networks:
      - public
    command:
      - --log.level=info
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
      - ./config/alertmanager:/etc/alertmanager

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 11025:1025 # SMTP
      - 18025:8025 # HTTP
    networks:
      - public
