version: "3.5"

networks:
  public: {}

volumes:
  grafana_data: {}
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.14.0
    ports:
      - 19090:9090
    networks:
      - public
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus:/etc/prometheus
    command:
      - --web.listen-address=0.0.0.0:9090
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --log.level=info

  grafana:
    image: grafana/grafana:6.5.1
    ports:
      - 13000:3000
    networks:
      - public
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pass
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=warn
